name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: studio-1063505923-cbb37
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure Firebase credentials
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          set -euo pipefail
          if [ -z "${FIREBASE_SERVICE_ACCOUNT:-}" ]; then
            echo "FIREBASE_SERVICE_ACCOUNT secret is not configured." >&2
            exit 1
          fi
          echo "$FIREBASE_SERVICE_ACCOUNT" > "$HOME/firebase_service_account.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_service_account.json" >> "$GITHUB_ENV"

      - name: Install Firebase CLI
        run: npm install --global firebase-tools

      - name: Enable Firebase web frameworks support
        run: firebase experiments:enable webframeworks --project "$FIREBASE_PROJECT_ID"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --non-interactive
