name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: firebase-hosting-${{ github.ref }}
  cancel-in-progress: true

env:
  FIREBASE_PROJECT_ID: studio-1063505923-cbb37

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure Firebase credentials
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          set -euo pipefail
          if [ -z "${FIREBASE_SERVICE_ACCOUNT:-}" ]; then
            echo "FIREBASE_SERVICE_ACCOUNT secret is not configured." >&2
            exit 1
          fi
          credentials_path="$HOME/firebase_service_account.json"
          echo "$FIREBASE_SERVICE_ACCOUNT" > "$credentials_path"
          chmod 600 "$credentials_path"
          {
            echo "GOOGLE_APPLICATION_CREDENTIALS=$credentials_path"
            echo "FIREBASE_CLI_LOGIN=service-account"
          } >> "$GITHUB_ENV"

      - name: Install Firebase CLI
        run: npm install --global firebase-tools@latest

      - name: Enable Firebase web frameworks support
        run: firebase experiments:enable webframeworks --project "$FIREBASE_PROJECT_ID"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --non-interactive
